# -*- coding: utf-8 -*-
"""llm type inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxdpzvqFeX_0LgBAUDpABvIpQvEqedyG
"""

# !pip install openai
!pip install mistralai

# from openai import OpenAI
import json
import time
import os
from pathlib import Path

from mistralai import Mistral
api_key = ""
client = Mistral(api_key=api_key)
model = "mistral-large-latest"

import zipfile
zip_path = "swe.zip"
extract_to = "sample_data/extracted"
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_to)

def infer_type(prompt,  pathname, filename):

    try:
      response = client.chat.complete(
          model= model,
          messages = [
              {
                  "role": "user",
                  "content": prompt,
              },
          ]
      )
      result = response.choices[0].message.content
      new_name = filename.replace(".txt",".pyi")
      new_file_path = os.path.join(pathname, new_name)
      print("new file path: ", new_file_path)
      with open(new_file_path, "w", encoding="utf-8") as f:
        f.write(result)

    except Exception as e:
      print("Error: ",e)
      return None

def read_all_files_as_string(directory_path: str) -> str:
      root_dir = Path("sample_data/extracted/swe")  # replace with your target directory
      all_txt_content = {}

      for txt_file in root_dir.rglob("*.txt"):
          with txt_file.open("r", encoding="utf-8") as f:
              all_txt_content[str(txt_file)] = f.read()

      for filename, content in all_txt_content.items():
          filename2 = os.path.basename(filename)
          dirpath = os.path.dirname(filename)
          infer_type(content,dirpath, filename2)



directory = "sample_data/prompts"  # Replace with your directory
all_content = read_all_files_as_string(directory)

!zip -r swe2.zip sample_data/extracted/swe

